<?php

use App\Models\User;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    'brand' =>  [
        'logo' => realpath(__DIR__.'/public/images/brand/logo.svg'),
        'color' => 'bg-green-800',
    ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => false,

    /*
    |--------------------------------------------------------------------------
    | Spark Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Spark to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        // Features::mustAcceptTerms(),
        // Features::euVatCollection(['home-country' => 'BE']),
        // Features::receiptEmails(['custom-addresses' => true]),
        // Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Yourmind.fitness',
        'product' => 'Affirm',
        'street' => '101 - 1860 Pandosy St',
        'location' => 'Kelowna, BC',
        'phone' => '587-873-0533',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'user' => [
            'model' => User::class,

            'trial_days' => 14,

            'default_interval' => 'monthly',

            'plans' => [
                [
                    'name' => 'Premium (Founder\'s Pricing)',
                    'short_description' => 'Special Founder\'s Pricing. Get access to the premium features to help improve your mental wellness journey.',
                    'monthly_id' => env('APP_ENV', 'local') === 'production' ? 'price_1Mh4ozA3c8c5pGuZN1vVoYNT' : 'price_1Mh50SA3c8c5pGuZGH59mipt',
                    'yearly_id' => env('APP_ENV', 'local') ==='production' ? 'price_1Mh4ozA3c8c5pGuZ81YKlRuS' : 'price_1Mh50SA3c8c5pGuZ5YramDdS',
                    'monthly_incentive' => 'Save 40%',
                    'yearly_incentive' => 'Save 50%',
                    'features' => [
                        'Premium at a discount price forever.',
                        'Focused Affirmation Categories',
                        'Schedulable Notifications (Coming Soon)',
                        'Your Wellness Tracking Metrics (Coming Soon)',
                        'Custom Backgrounds (Future Updates)',
                        'Custom Affirmations (Future Updates)',
                    ],
                    'archived' => false,
                ],
                [
                    'name' => 'Premium',
                    'short_description' => 'Get access to the premium features to help improve your mental wellness journey.',
                    'monthly_id' => env('APP_ENV', 'local') === 'production' ? 'price_1Mf9LfA3c8c5pGuZ6Pl5WcqH' : 'price_1Mf9OiA3c8c5pGuZnoQCsB7V',
                    'yearly_id' => env('APP_ENV', 'local') ==='production' ? 'price_1Mf9MUA3c8c5pGuZxTp0OUru' : 'price_1Mf9P5A3c8c5pGuZ34MIk1KY',
                    'yearly_incentive' => 'Save 20%',
                    'features' => [
                        'Focused Affirmation Categories',
                        'Schedulable Notifications (Coming Soon)',
                        'Your Wellness Tracking Metrics (Coming Soon)',
                        'Custom Backgrounds (Future Updates)',
                        'Custom Affirmations (Future Updates)',
                    ],
                    'archived' => false,
                ],
                
            ],

        ],
    ],
];
