name: Cloudways API Git Pull

on:
  pull_request:
    branches:
      - staging

  push:
    branches:
      - staging

jobs: 
  tag:
    name: Deploy Staging

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with: 
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: 8.1

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Run Composer
        run: composer install --no-interaction 

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present

      - name: Extract Build
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB#refs/heads/})"
        id: extract_branch

      - name: Commit Changes
        uses: stefanweifel/git-auto-commit-action@v4
        with:
          commit_message: Build Project
          branch: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Cloudways API Git Pull
      #   uses: roelmagdaleno/cloudways-api-git-pull-action@stable
      #   with:
      #     email: ${{ secrets.CLOUDWAYS_EMAIL }}
      #     api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
      #     server-id: ${{ secrets.CLOUDWAYS_SERVER_ID }}
      #     app-id: ${{ secrets.CLOUDWAYS_APP_ID }}
      #     branch-name: ${{ secrets.CLOUDWAYS_BRANCH_NAME }}
      #     deploy-path: ${{ secrets.CLOUDWAYS_DEPLOY_PATH }}
